apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: "{{.Release.Name}}-elasticsearch"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: server
    app: "{{.Release.Name}}-elasticsearch"
spec:
  serviceName: "elasticsearch"
  replicas: 1
  template:
    metadata:
      labels:
        release: {{.Release.Name | quote }}
        component: server
        app: "{{.Release.Name}}-elasticsearch"
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-allinone
        image: "{{.Values.ElasticSearchImage}}:{{.Values.ElasticSearchImageTag}}"
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: esdb
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms{{.Values.ESHeapSize}} -Xmx{{.Values.ESHeapSize}}"
        livenessProbe:
          tcpSocket:
            port: 9300
          initialDelaySeconds: 30
          timeoutSeconds: 3
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        volumeMounts:
        - mountPath: /data
          name: data-volume
  volumeClaimTemplates:
  - metadata:
      name: data-volume
      annotations:
      {{if .Values.ESDataStorageClass}}
        volume.beta.kubernetes.io/storage-class: "{{ .Values.ESDataStorageClass }}"
      {{else}}
        volume.alpha.kubernetes.io/storage-class: default
      {{end}}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.ESDataStorageSize }}