apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{.Release.Name}}-curator"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: curator
    app: "{{.Release.Name}}-elasticsearch"
spec:
  schedule: "*/5 * * * *"
  startingDeadlineSeconds: 30
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: "{{.Values.CuratorImage}}:{{.Values.CuratorTag}}"
            args:
            - --config
            - /etc/config/config.yml
            - /etc/config/action_file.yml
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: "{{.Release.Name}}-curator-config"
          restartPolicy: OnFailure