kind: Service
apiVersion: v1
metadata:
  name: "{{ printf "%s-kibana" .Release.Name | trunc 24 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: kibana
    app: "{{.Release.Name}}-elasticsearch"
spec:
  ports:
  - port: 5601
  selector:
    component: kibana
    app: "{{.Release.Name}}-elasticsearch"