kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: "{{.Release.Name}}-kibana"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: kibana
    app: "{{.Release.Name}}-elasticsearch"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kibana
      app: "{{.Release.Name}}-elasticsearch"
  minReadySeconds: 3
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: kibana
        app: "{{.Release.Name}}-elasticsearch"
    spec:
      containers:
      - name: kibana-logging
        image: "{{.Values.KibanaImage}}:{{.Values.KibanaImageTag}}"
        env:
          - name: ELASTICSEARCH_URL
            value: http://{{.Release.Name}}-elasticsearch:9200
        ports:
          - containerPort: 5601